project_name: 'sttr'

# before are hooks that will be run before any builds are done, so good to put install scripts and stuff that your builds need here
before:
  hooks:
    # Remove unused packaged from the build process
    - go mod tidy
    - go generate


builds:
  - main: ./main.go
    binary: sttr
    goos: ['linux', 'darwin', 'windows']
    goarch: ['386', 'amd64']
    env:
      - CGO_ENABLED=0

changelog:
  sort: 'asc'
  filters:
    exclude: ['^docs:', 'demo', '^hugo:', 'Merge pull request', 'Merge branch']

brews:
  - tap:
      owner: abhimanyu003
      name: homebrew-sttr
    name: sttr
    homepage: "https://github.com/abhimanyu003/sttr"
    description: "A cross-platform, cli app to perform various string operations."
    license: "MIT"
    skip_upload: auto
    commit_author:
      name: abhimanyu003
      email: abhimanyusharma003@gmail.com
    folder: Formula
    install: |-
      bin.install "sttr"
    test: |
      system "#{bin}/sttr -v"

snapcrafts:
  - name: sttr
    publish: true
    summary: A cross-platform, cli app to perform various operations on string.
    description: |
      sttr is command line software that allows you to quickly run various transformation operations on the string.
    grade: stable
    confinement: classic
    license: MIT
    base: core20

    apps:
      sttr:
        plugs: ["home", "network"]