project_name: "sttr"
version: 2
# before are hooks that will be run before any builds are done, so good to put install scripts and stuff that your builds need here
before:
  hooks:
    # Remove unused packaged from the build process
    - go mod tidy
    - go generate

builds:
  - main: ./main.go
    binary: sttr
    goos: ["linux", "darwin", "windows"]
    goarch: ["386", "amd64", "arm64"]
    ldflags:
      - -s -w -X "main.version={{.Version}}"
    env:
      - CGO_ENABLED=0

universal_binaries:
  - replace: true

changelog:
  sort: "asc"
  filters:
    exclude: ["^docs:", "demo", "^hugo:", "Merge pull request", "Merge branch"]

brews:
  - repository:
      owner: abhimanyu003
      name: homebrew-sttr
    name: sttr
    homepage: "https://github.com/abhimanyu003/sttr"
    description: "A cross-platform, cli app to perform various string operations."
    license: "MIT"
    skip_upload: auto
    commit_author:
      name: abhimanyu003
      email: abhimanyusharma003@gmail.com
    directory: Formula
    install: |-
      bin.install "sttr"
    test: |
      system "#{bin}/sttr -v"

scoops:
  - repository:
      owner: abhimanyu003
      name: scoop-bucket
      token: "{{ .Env.GITHUB_TOKEN }}"
    name: sttr
    homepage: "https://github.com/abhimanyu003/sttr"
    description: "sttr is command line software that allows you to quickly run various transformation operations on the string."
    license: "MIT"

nfpms:
  - builds:
      - sttr
    vendor: abhimanyu003
    homepage: "https://github.com/abhimanyu003/sttr/"
    maintainer: "Abhimanyu Sharma <abhimanyusharma003@gmail.com>"
    description: "A cross-platform, cli app to perform various operations on string"
    license: MIT
    formats:
      - deb
      - rpm
      - termux.deb
    bindir: /usr/bin

snapcrafts:
  - name: sttr
    publish: true
    summary: A cross-platform, cli app to perform various operations on string.
    description: |
      sttr is command line software that allows you to quickly run various transformation operations on the string.
    grade: stable
    confinement: strict
    license: MIT
    base: core20

    apps:
      sttr:
        plugs: ["home", "network"]

aurs:
  - name: sttr-bin
    homepage: "https://github.com/abhimanyu003/sttr"
    description: "sttr is command line software that allows you to quickly run various transformation operations on the string."
    maintainers:
      - "Abhimanyu Sharma <abhimanyusharma003@gmail.com>"
    license: "MIT"
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/sttr-bin.git"
    commit_author:
      name: Abhimanyu Sharma
      email: abhimanyusharma003@gmail.com

chocolateys:
  - name: sttr
    title: sttr - A cross-platform, cli app to perform various operations on string.
    authors: Abhimanyu Sharma
    project_url: https://github.com/abhimanyu003/sttr
    url_template: "https://github.com/abhimanyu003/sttr/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    icon_url: https://cdn.jsdelivr.net/gh/abhimanyu003/sttr@main/media/logo.png
    copyright: 2023 Abhimanyu Sharma
    license_url: https://github.com/abhimanyu003/sttr/blob/main/LICENSE
    require_license_acceptance: false
    project_source_url: https://github.com/abhimanyu003/sttr
    docs_url: https://github.com/abhimanyu003/sttr/blob/main/README.md
    bug_tracker_url: https://github.com/abhimanyu003/sttr/issues
    tags: "productivity encoding terminal string decoding tui developer-tools transform cli-app encrypt encryption-decryption count-lines devutils tui-app count-words zeropad"
    summary: A cross-platform, cli app to perform various operations on string.
    description: |
      sttr installer package.
      A cross-platform, cli app to perform various operations on string.
    release_notes: "https://github.com/abhimanyu003/sttr/releases/tag/v{{ .Version }}"
    api_key: "{{ .Env.CHOCOLATEY_API_KEY }}"
    source_repo: "https://push.chocolatey.org/"
    skip_publish: true

sboms:
  - artifacts: archive
